name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - "stable"

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - run: dart pub global activate melos

      - name: Install dependencies
        run: melos bootstrap

      - name: Run tests
        run: melos run analyze

      - name: Run tests
        run: melos run test:all   

      - name: "Pub Check"
        run: |
          melos exec -c 1 --no-private --ignore="*example*" -- \
            pub publish --dry-run

